#! /usr/bin/perl

#################################################################
#	The PKG Object
#################################################################

use strict;

use Data::Dumper;
$Data::Dumper::Sortkeys = 1;

package Pkg;

#################################################################
# Class Variables
#################################################################

our @All = ();
our %Named = ();
our %Owner = ();

our %File = ();

#################################################################
# Class Functions
#################################################################

sub name
{
	my $self = shift;
	$self->{name};
}

#################################################################
# Initialize Name/Version/Release/Arch
#	format: /path/name-release-version.arch.rpm
#################################################################

sub gename
{
	my $self = shift;

	my @file = split(/\//, $self->{pkg});
	$self->{file} = pop(@file);		# last is file
	$self->{dir}  = join('/', @file);	# others are dirs

	my @name = split(/-/, $self->{file});
	$self->{rel} = pop(@name);		# last is release
	$self->{ver} = pop(@name);		# next is version
	my $name = join('-', @name);		# rest is name
	$self->{name} = $name;

	push(@Pkg::All, $Pkg::Named{$name} = $self);

	my @arch = split(/\./, $self->{rel});
	pop @arch ; # nuke .rpm suffix		# last is '.rpm'
	$self->{arch} = pop(@arch);		# next is arch
	$self->{rel} = join('.', @arch);	# rest is release

}

#################################################################
# Initialize Provides List
#################################################################

sub genpro
{
	my $self = shift;
	my ($key, $val);

	chomp(my @pro  = `rpm -qp --provides $self->{pkg}`);
	$self->{PRO} = [ @pro ];
	$self->{pro} = { };
	for (@pro)
	{
		s/ //g;				# nuke whitespace
		next if /[()]/;			# parens evil
		$val = $key = $_;
		$key =~ s/[<=>()].*//;		# find key
		$val =~ s/.*[<=>()]//;		# find value

		$self->{pro}{$key} = $val;	# store
	}
}

#################################################################
# Initialize Provides List
#################################################################

sub genreq
{
	my $self = shift;
	my ($key, $val);

	chomp(my @req  = `rpm -qp --requires $self->{pkg}`);
	$self->{REQ} = [ @req ];
	$self->{req} = { };
	for (@req)
	{
		s/ //g;
		next if /[()]/;
		$val = $key = $_;
		$key =~ s/[<=>()].*//;
		$val =~ s/.*[<=>()]//;

		$self->{req}{$key} = $val;
	}
}

#################################################################
# Initialize Provides List
#################################################################

sub genlist
{
	my $self = shift;
	my $name = $self->{name};
	chomp(my @list = `rpm -qp --list     $self->{pkg}`);
	map	{ s/ //g; }		@list;
	map	{ $Owner{$_} = $name; }	@list;
}

#################################################################
# Constructor
#################################################################

sub new
{
	my $class = shift;
	my $pkg   = shift;

warn "new($class, $pkg)\n" ;

	warn("ERROR: Not a Package File: $pkg\n") && return undef 
		unless ($pkg =~ /\.rpm$/);

	my $self = {
		pkg	=> $pkg,
		line	=> 0,
		lvl	=> 0,
	};

#	push @All, $self;

	bless $self, $class;

	$self->gename;
	$self->genpro;
	$self->genreq;
	$self->genlist;

	return $self ;
}

#################################################################
#	Global Variables
#################################################################

package main;

our @ARGS = @ARGV;
our $Line = 0;
our $Lvl = 0;
#our @Pkg = ();
#our %Pkg = ();

#################################################################
#	Model: Read Package Info
#################################################################

sub snarf
{
	while (my $pkg = shift)
	{
#warn("snarf($pkg)\n");
		my $p = Pkg->new($pkg);
#		push(@Pkg, $Pkg{$p->{name}} = $p);
	}
}

#################################################################
#	Model: Dump
#################################################################

sub splat
{
	print(Data::Dumper->Dump([ \%Pkg::All   ], [ '*Pkg::All'   ]));
	print(Data::Dumper->Dump([ \%Pkg::Named ], [ '*Pkg::Named  ]));
	print(Data::Dumper->Dump([ \%Pkg::Owner ], [ '*Pkg::Owner' ]));
#	print(Data::Dumper->Dump([ \%Pkg  ], [ '*Pkg'  ]));
#	print(Data::Dumper->Dump([ \%File ], [ '*File' ]));
}

#################################################################
#	Main Program
#################################################################

sub main
{
	snarf(@_);
	splat;
}

main(@ARGV);
